# Database settings
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.address=0.0.0.0

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# API Documentation settings
springdoc.api-docs.path=/api/docs
springdoc.swagger-ui.path=/api/swagger-ui.html^
