name: Build and Deploy Docker image to Azure

on:
  push:
    branches:
      - main
      - devel      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nutrifier:${IMAGE_TAG} .

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          docker push ${{ secrets.DOCKER_USERNAME }}/nutrifier:${IMAGE_TAG}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref == 'refs/heads/main' && 'nutrifier-prod' || 'nutrifier-dev' }} 'nutrifier'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
